FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

RUN pip install dash plotly pandas

COPY ./task2 /app/task2

CMD ["python", "task2/app.py"]
