FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

RUN pip install pandas matplotlib reportlab

COPY ./task1 /app/task1

CMD ["python", "task1/app.py"]
