version: '3.8'
services:
  db:
    image: postgres:15
    container_name: crm_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Test1234
      POSTGRES_DB: crmdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./task1/data:/data
      - db_data:/var/lib/postgresql/data

  dash:
    build:
      context: .
      dockerfile: Dockerfile.dash
    container_name: crm_dash
    ports:
      - "8050:8050"
    volumes:
      - ./task1:/app/task1
    depends_on:
      - db

volumes:
  db_data:
